PS-8047 - Fix warning unused variable in gtidset.cpp
https://jira.percona.com/browse/PS-8047

---

*Problem*:

gcc-7 compilation fails with the following error:

```
/home/vsts/work/1/s/libbinlogevents/src/gtids/gtidset.cpp:238:36: error: unused variable ‘uuid’ [-Werror=unused-variable]
   for (auto const &[uuid, intervals] : m_gtid_set) {
```
                                    ^
*Solution*:

gcc 7 has no implemented `[[maybe_unused]]` for structure bindings so
use pragmas to silent the warning.