PS-8185 - Include missing header in pfs_name.h
**Problem:**

The compilation in some platforms are failing:

```
In file included from /work/ps/src/8.0/storage/perfschema/pfs_prepared_stmt.h:35,
                 from /work/ps/src/8.0/storage/perfschema/pfs_prepared_stmt.cc:32:
/work/ps/src/8.0/storage/perfschema/pfs_name.h: In instantiation of 'PFS_any_name<max_length>& PFS_any_name<max_length>::operator=(const PFS_any_name<max_length>&) [with int max_length = 192]':
/work/ps/src/8.0/storage/perfschema/pfs_name.h:204:20:   required from here
/work/ps/src/8.0/storage/perfschema/pfs_name.h:63:13: error: 'memcpy' was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
   63 |       memcpy(m_data, other.m_data, m_length);
      |       ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /work/ps/src/8.0/include/sql_string.h:34,
                 from /work/ps/src/8.0/include/lf.h:41,
                 from /work/ps/src/8.0/storage/perfschema/pfs_instr.h:57,
                 from /work/ps/src/8.0/storage/perfschema/pfs_program.h:35,
                 from /work/ps/src/8.0/storage/perfschema/pfs_prepared_stmt.h:36,
                 from /work/ps/src/8.0/storage/perfschema/pfs_prepared_stmt.cc:32:
/usr/include/string.h:43:14: note: 'void* memcpy(void*, const void*, size_t)' declared here, later in the translation unit
   43 | extern void *memcpy (void *__restrict __dest, const void *__restrict __src,
      |              ^~~~~~
```

`memcpy` is used without having include the header defining it.

**Solution:**

Include the header which defines `memcpy`.