PS-8047 - Fix warning unused variable in gtidset.cpp
https://jira.percona.com/browse/PS-8047

---

*Problem*:

gcc-7 compilation fails with the following error:

```
/home/vsts/work/1/s/libbinlogevents/src/gtids/gtidset.cpp:238:36: error: unused variable ‘uuid’ [-Werror=unused-variable]
   for (auto const &[uuid, intervals] : m_gtid_set) {
```
                                    ^
*Solution*:

There is no way of setting as `[[maybe_unused]]` just one variable part
of a structure binding so all the variables have to be marked as that.