Fix bug 880268: with MySQL 5.5.16, plugin compilation gives:
auth_pam.c:303:1: error: missing initializer [-Werror=missing-field-initializers]
auth_pam.c:303:1: error: (near initialization for ‘_mysql_plugin_declarations_[0].flags’) [-Werror=missing-field-initializers]
auth_pam.c:318:2: error: missing initializer [-Werror=missing-field-initializers]
auth_pam.c:318:2: error: (near initialization for ‘_mysql_plugin_declarations_[1].flags’) [-Werror=missing-field-initializers]
cc1: all warnings being treated as errors

MySQL 5.5.16 has introduced new flags field in st_plugin struct and
has bumped MYSQL_PLUGIN_INTERFACE_VERSION.

Fix by initializing it.