Fix PS-5328 (fil0crypt.h:123:7: error: 'memset_s' was not declared in this scope on illumos)
memset_s in C11 is only guaranteed to be available if
__STDC_LIB_EXT1__ is defined by the implementation and if user defines
__STDC_WANT_LIB_EXT1__, which we didn't do. Thus add the latter define
to CMake default defines, before the feature checks.