[myrocks] PS-9764 fix: Add clang-20 to Azure Pipelines and fix clang-20 compilation issues
https://perconadev.atlassian.net/browse/PS-9764

Fixed the following issue with calling 'memset()' on a
nontrivially-constructed object ('TREE') by calling the placement new
operator with empty brace initializer '{}' instead:
/percona-server-8.0/storage/myisam/ft_boolean_search.cc:531:10: error: first argument in call to 'memset' is a pointer to non-trivially copyable type 'TREE' [-Werror,-Wnontrivial-memcall]
  531 |   memset(&ftb->no_dupes, 0, sizeof(TREE));
      |          ^

Fixed the following group of issues with calling 'memset()' on
nontrivially-constructed objects ('TREE', 'MI_SORT_PARAM', 'MI_INFO') by
declaring those objects with empty brace initializer '{}':
/percona-server-8.0/storage/myisam/ft_nlq_search.cc:241:10: error: first argument in call to 'memset' is a pointer to non-trivially copyable type 'TREE' [-Werror,-Wnontrivial-memcall]
  241 |   memset(&wtree, 0, sizeof(wtree));
      |          ^

/home/yura/ws/percona-server-8.0/storage/myisam/myisamchk.cc:1404:10: error: first argument in call to 'memset' is a pointer to non-trivially copyable type 'MI_SORT_PARAM' [-Werror,-Wnontrivial-memcall]
 1404 |   memset(&sort_param, 0, sizeof(sort_param));
      |          ^

/home/yura/ws/percona-server-8.0/storage/myisam/mi_open.cc:122:10: error: first argument in call to 'memset' is a pointer to non-trivially copyable type 'MI_INFO' [-Werror,-Wnontrivial-memcall]
  122 |   memset(&info, 0, sizeof(info));
      |          ^

The following warning suppressed as it comes from the 'rocksdb' submodule
code:
/percona-server-8.0/storage/rocksdb/rocksdb/port/mmap.cc:46:15: error: first argument in call to 'memcpy' is a pointer to non-trivially copyable type 'rocksdb::MemMapping' [-Werror,-Wnontrivial-memcall]
   46 |   std::memcpy(this, &other, sizeof(*this));
      |               ^

Fixed the following literal operator warning:
/percona-server-8.0/storage/temptable/include/temptable/constants.h:36:48: error: identifier '_KiB' preceded by whitespace in a literal operator declaration is deprecated [-Werror,-Wdeprecated-literal-operator]
   36 | inline constexpr unsigned long long operator"" _KiB(
      |                                     ~~~~~~~~~~~^~~~
      |                                     operator""_KiB

Fixed the following extra semicolon warning in NDB code:
/percona-server-8.0/storage/ndb/src/kernel/vm/Configuration.cpp:653:2: error: extra ';' outside of a function is incompatible with C++98 [-Werror,-Wc++98-compat-extra-semi]
  653 | };
      |  ^

Removed adding '-Wno-enum-constexpr-conversion' to the compiler options for
clang >= 18 for 'sql_gis' as this option no longer exists in the 'clang-20'
and Oracle fixed this issue properly in Bug #36292498
"Compile MySQL with clang 18 [noclose]"
(commit mysql/mysql-server@5e066e70ebb).