Fix the compilation warnings (bug 878164):
- sql/log.cc: In function ‘void mysql_bin_log_commit_pos(THD*, ulonglong*, const char**)’:
  sql/log.cc:7116:15: error: converting to non-pointer type ‘ulonglong
  {aka long long unsigned int}’ from NULL [-Werror=conversion-null]

- storage/innobase/btr/btr0sea.c: In function
  ‘btr_search_drop_page_hash_index’:
  storage/innobase/btr/btr0sea.c:1070:16: error: unused parameter
  ‘index_in’ [-Werror=unused-parameter]

- storage/innobase/buf/buf0buf.c: In function ‘buf_pool_watch_set’:
  storage/innobase/buf/buf0buf.c:1607: warning: ‘block_mutex’ may be
  used uninitialized in this function

The fixes:

- innodb_adaptive_hash_index_partitions.patch: remove unused second
  arg of btr_search_drop_page_hash_index, update all callers.
- group_commmit.patch: set ulonglong variable with 0ULL, not NULL.
- innodb_split_buf_pool_mutex.patch: join two identical if statements,
  as a bonus the first one will get a branch prediction too.