Fix bug 902467:
os/os0file.c: In function ‘os_aio_simulated_wake_handler_thread’:
os/os0file.c:3596:9: error: variable ‘segment’ set but not used
[-Werror=unused-but-set-variable]
os/os0file.c: In function ‘os_aio_simulated_handle’:
os/os0file.c:4081:9: error: variable ‘segment’ set but not used
[-Werror=unused-but-set-variable]

log.cc: In member function ‘bool LOGGER::slow_log_print(THD*, const
char*, uint, ulonglong)’:
log.cc:998:12: error: variable ‘current_time’ set but not used
[-Werror=unused-but-set-variable]

sql_show.cc: In function ‘int store_create_info(THD*, TABLE_LIST*,
String*, HA_CREATE_INFO*, bool)’:
sql_show.cc:1254:8: error: variable ‘show_table_options’ set but not
used [-Werror=unused-but-set-variable]

The fix is to remove those variables, or, in case of
show_table_options, surround with the same #ifdef guard as the code
that uses the value.