[components/keyrings/common] PS-9823 fix: mysql_migrate_keyring won't work with PS's components
https://perconadev.atlassian.net/browse/PS-9823

Reworked keyring components to make sure their corresponding '.so' objects do not have unresolved symbols (from the 'dlopen(..., RTLD_NOW)' point of view). This change is needed to ensure that keyring components can be loaded not only from the 'mysqld' executable but from utilities like 'mysql_migrate_keyring' as well.

Keyring components' 'CMakeLists.txt' files fortified with aditional linking option '${LINK_FLAG_NO_UNDEFINED}' (-Wl,--no-undefined) which prevents building '.so' shared objects with unresolved sumbols.

Removed custom allocator from the 'components/keyrings/common/data/pfs_string.h' header
to eliminate divergence from upstream code. 'pfs_string' kept as an alias to 'std::string' to
minimize Percona code changes.

Removed 'DBUG_TRACE' calls from the 'component_keyring_kmip' code to get rid of 'mysys' library dependency.

Calls to 'mysql_components_handle_std_exception()' inside 'component_keyring_kmip'
replaced with 'LogComponentErr()' to avoid dependency on 'minchassis'.

'memset_s()' Percona's extension function renamed to 'my_memset_s()'.

Added a series of 'component_keyring_xxx.dynamic_loading' MTR test cases (one for each keyring component: 'file', 'kmip', 'kms') that checks if the component's '.so' file does not have unresolved symbols in order to make sure that it can be loaded from auxiliary utilities (like 'mysql_migrate_keyring'). These MTR test cases internally build a helper utility from the '.cpp' file ('mysql-test/std_data/dlopen_checker.cpp') that simply performs an attempt to call 'dlopen(..., RTLD_NOW)' for the provided '.so' object.

Added 'keyring_vault.migrate_keyring' MTR test case that tests for keyring data migration from 'keyring_vault' plugin to 'keyring_file' plugin and back. Internally, it uses 'mysqld' executable
in keyring data migration mode to perform key stansfer from one plugin to another.

Added 'have_keyring_file_plugin.inc' MTR include file that helps to identify if the server was
build with 'keyring_file' plugin.

Removed 'have_keyring_kmip_plugin.inc' MTR include file added previously by mistake.

-----------------------------------------------------------------------------------

PS-10166 [8.0]: Improve stability of `component_keyring_file.dynamic_loading`

On some platforms we see the following issue:
```
CURRENT_TEST: component_keyring_file.dynamic_loading /usr/bin/ld: /tmp/ccg7pao0.o: in function main::{lambda(void*)#1}::operator()(void*) const': dlopen_checker.cpp:(.text+0x1f): undefined reference to dlclose' /usr/bin/ld: /tmp/ccg7pao0.o: in function main': dlopen_checker.cpp:(.text+0xa9): undefined reference to dlopen' /usr/bin/ld: dlopen_checker.cpp:(.text+0xf8): undefined reference to dlerror' collect2: error: ld returned 1 exit status mysqltest: At line 20: Command "g++ -std=c++17 -ldl -o $dlopen_checker_binary $dlopen_checker_source" failed.
```

This error occurs because the linker flag -ldl (for linking against the dynamic loading library, libdl) is placed before the source file instead of after it in your g++ command.

In GCC and Clang, order matters — libraries must come after the objects or source files that reference them.