PS-8047 - Fix compilation of pfs_instr-t
https://jira.percona.com/browse/PS-8047

---

*Problem*:

gcc-7 compilation fails with the following error:

```
ld.lld: error: duplicate symbol: log_message(int, ...)
```
                                    ^
The function is defined in `pfs_server_stubs` and `sql_main`.

*Solution*:

Remove inclusion of `sql_main` which is not necessary.