PS-8674 Compilation error on ARM AppleClang 14.0 https://jira.percona.com/browse/PS-8674
Disabled the PERCONA_AUTHENTICATION_LDAP on APPLE ARM
because of compilation error

undefined symbols for architecture arm64:
  "_ldap_set_urllist_proc", referenced from:
ld: symbol(s) not found for architecture arm64

The problem with MacOS system libraries.