[azure] PS-8169: Initial implementation of the authentication_ldap_sasl plugin
This commit adds the server side plugin for SASL LDAP authentication.
The client side is already present in the sources.

A high level overview of the authentication process is also described
in the readme file in the plugin directory.

PS-8330 merge: Merge MySQL 8.0.30 - Q3 2022 (macos ldap_simple / ldap_sals fix) (#4915)

https://jira.percona.com/browse/PS-8330

Introduced new 'WITH_PERCONA_AUTHENTICATION_LDAP' top-level CMake
option that controlls if Percona's 'authentication_ldap_simple' and
'authentication_ldap_sasl' are included in the build.

Fixed 'authentication_ldap_simple' / 'authentication_ldap_sasl' plugin
dependencies: instead ofthe hardcoded 'ldap_r' we now use
'${LDAP_LIBRARY} ${LBER_LIBRARY}' detected in the 'ldap.cmake'.

Azure Pipelines configuration file updated so that
'authentication_ldap_simple' / 'authentication_ldap_sasl' are not built
on MacOS.

-------------------------------------------------------------------------------------

PS-8674 Compilation error on ARM AppleClang 14.0
https://jira.percona.com/browse/PS-8674

Disabled the PERCONA_AUTHENTICATION_LDAP on APPLE ARM
because of compilation error

undefined symbols for architecture arm64:
  "_ldap_set_urllist_proc", referenced from:
ld: symbol(s) not found for architecture arm64

The problem with MacOS system libraries.