PS-9609 postfix: audit_log_filter can't be installed when server is using component_keyring_kmip
https://perconadev.atlassian.net/browse/PS-9609

Fixed problem with passing a 'std::string' via va_args into printf-like
function that expects 'const char *`.

error: cannot pass object of non-trivial type 'basic_string<char, char_traits<char>, Malloc_allocator<char>>' through variadic method; call will abort at runtime [-Wnon-pod-varargs]