PS-7032: fix gcc-10 compilation issues (5.7)
1. Fix gcc-10 issue:
```
In file included from /data/mysql-server/mysql-5.7/include/my_global.h:80,
                 from /data/mysql-server/mysql-5.7/sql/sql_parse.h:26,
                 from /data/mysql-server/mysql-5.7/sql/auth/sql_user.cc:22:
/data/mysql-server/mysql-5.7/sql/auth/sql_user.cc: In function ‘void append_user(THD*, String*, LEX_USER*, bool, bool)’:
/data/mysql-server/mysql-5.7/sql/auth/sql_user.cc:125:52: error: suggest parentheses around assignment used as truth value [-Werror=parentheses]
  125 |           DBUG_ASSERT(thd->variables.old_passwords = 2);
```

2. Fix gcc-10 compilation issues with MyRocks:
```
In file included from /usr/include/c++/10/memory:83,
                 from /data/mysql-server/percona-5.7/storage/rocksdb/rocksdb/include/rocksdb/db.h:14,
                 from /data/mysql-server/percona-5.7/storage/rocksdb/rocksdb/include/rocksdb/ldb_tool.h:9,
                 from /data/mysql-server/percona-5.7/storage/rocksdb/rocksdb/tools/ldb_tool.cc:7:
/usr/include/c++/10/bits/unique_ptr.h: In instantiation of ‘constexpr std::unique_ptr<_Tp, _Dp>::unique_ptr() [with _Del = std::default_delete<rocksdb::WriteBatch>; <template-parameter-2-2> = void; _Tp = rocksdb::WriteBatch; _Dp = std::default_delete<rocksdb::WriteBatch>]’:
/data/mysql-server/percona-5.7/storage/rocksdb/rocksdb/include/rocksdb/transaction_log.h:63:17:   required from here
/usr/include/c++/10/bits/unique_ptr.h:269:9: error: no matching function for call to ‘std::__uniq_ptr_data<rocksdb::WriteBatch, std::default_delete<rocksdb::WriteBatch>, true, true>::__uniq_ptr_data()’
  269 |  : _M_t()
      |         ^
/usr/include/c++/10/bits/unique_ptr.h:209:40: note: candidate: ‘std::__uniq_ptr_data<rocksdb::WriteBatch, std::default_delete<rocksdb::WriteBatch>, true, true>::__uniq_ptr_data(std::__uniq_ptr_impl<rocksdb::WriteBatch, std::default_delete<rocksdb::WriteBatch> >::pointer) [inherited from std::__uniq_ptr_impl<rocksdb::WriteBatch, std::default_delete<rocksdb::WriteBatch> >]’
  209 |       using __uniq_ptr_impl<_Tp, _Dp>::__uniq_ptr_impl;
```