Fix flaky rocksdb.partial_index_stress MTR
Upstream commit ID: https://github.com/facebook/mysql-5.6/commit/c1f79a85e126
PS-9395: Merge percona-202401 (https://jira.percona.com/browse/PS-9395)

Summary:
sometime rocksdb.partial_index_stress MTR fail especially under myrocks DD due
```
MySQLdb._exceptions.OperationalError: (1213, 'Deadlock found when trying to get lock; try restarting transaction (snapshot conflict)')
```

From https://dev.mysql.com/doc/refman/8.0/en/set-transaction.html, SET SESSION TRANSACTION doesn't apply to cur trx.

The fix is to commit Isolation change first to avoid snapshot conflict during first insert

Differential Revision: D50420444